---
name: flake-templates

path: .

windows:
  - name: code
    flex_direction: column
    panes:
      - commands:
          - command: $EDITOR
        flex: 9
        zoom: true
        focus: true
      - flex: 1

  - name: misc
    panes:
      - flex: 1
        focus: true
      - flex: 1
