[package]
name = "my-app"
version = "0.0.1"
edition = "2021"
description = "A simple rust app."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
